version: '3.8'
name: aiml-infrastructure
services:

  postgres:
    restart: unless-stopped
    image: postgres:13.7
    container_name: aiml_postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Etc/GMT
      - PGTZ=Etc/GMT
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "${POSTGRES_PORT}", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - monitoring

  pgadmin:
    image: dpage/pgadmin4
    container_name: aiml_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aiml.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80

  prometheus:
    image: prom/prometheus
    container_name: aiml_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring

  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: aiml_postgres_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      prometheus:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: aiml_grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_USER_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
  
  minio:
    restart: unless-stopped
    image: quay.io/minio/minio:latest
    container_name: aiml_minio
    volumes:
      - ./minio/data:/home/data
      - ./minio/certs:/home/certs
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:443
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ADDRESS=${MINIO_ADDRESS}
      - MINIO_CONSOLE_ADDRESS=${MINIO_CONSOLE_ADDRESS}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_STORAGE_USE_HTTPS=${MINIO_STORAGE_USE_HTTPS}
    command: server ${MINIO_DATA_DIR} --certs-dir ${MINIO_CERT_DIR}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:${MINIO_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mlflow:
    restart: unless-stopped
    build: ./mlflow
    image: aiml_mlflow
    container_name: aiml_mlflow
    depends_on:
      - postgres
      - minio
    ports:
      - ${MLFLOW_PORT}:5000
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - MLFLOW_S3_IGNORE_TLS=${MLFLOW_S3_IGNORE_TLS}
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${MLFLOW_DB}
      --artifacts-destination s3://${MLFLOW_BUCKET_NAME}
    healthcheck:
      test: ["CMD","curl", "-f", "http://host.docker.internal:${MLFLOW_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  prom_data:

networks:
  monitoring:
    driver: bridge